// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StateMachineExperiments.Data;

#nullable disable

namespace StateMachineExperiments.Migrations
{
    [DbContext(typeof(LodDbContext))]
    partial class LodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("StateMachineExperiments.Modules.FormalLOD.Models.FormalLineOfDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppealFiled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentState")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeterminationResult")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestigatingOfficerId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestigatingOfficerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InvestigationCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InvestigationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeathCase")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<bool>("ToxicologyComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToxicologyRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("FormalLodCases");
                });

            modelBuilder.Entity("StateMachineExperiments.Modules.FormalLOD.Models.FormalStateTransitionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormalLodCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedByAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormalLodCaseId");

                    b.ToTable("FormalTransitionHistory");
                });

            modelBuilder.Entity("StateMachineExperiments.Modules.InformalLOD.Models.InformalLineOfDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppealFiled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentState")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InjurySeverity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresLegalReview")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresWingReview")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("LodCases");
                });

            modelBuilder.Entity("StateMachineExperiments.Modules.InformalLOD.Models.StateTransitionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LodCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedByAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LodCaseId");

                    b.ToTable("TransitionHistory");
                });

            modelBuilder.Entity("StateMachineExperiments.Modules.FormalLOD.Models.FormalStateTransitionHistory", b =>
                {
                    b.HasOne("StateMachineExperiments.Modules.FormalLOD.Models.FormalLineOfDuty", "FormalLodCase")
                        .WithMany("TransitionHistory")
                        .HasForeignKey("FormalLodCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormalLodCase");
                });

            modelBuilder.Entity("StateMachineExperiments.Modules.InformalLOD.Models.StateTransitionHistory", b =>
                {
                    b.HasOne("StateMachineExperiments.Modules.InformalLOD.Models.InformalLineOfDuty", "LodCase")
                        .WithMany("TransitionHistory")
                        .HasForeignKey("LodCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LodCase");
                });

            modelBuilder.Entity("StateMachineExperiments.Modules.FormalLOD.Models.FormalLineOfDuty", b =>
                {
                    b.Navigation("TransitionHistory");
                });

            modelBuilder.Entity("StateMachineExperiments.Modules.InformalLOD.Models.InformalLineOfDuty", b =>
                {
                    b.Navigation("TransitionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
